"""create book table

Revision ID: 8037bbb1976b
Revises:
Create Date: 2026-09-24 19:19:05.908208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8037bbb1976b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer, nullable=False, autoincrement=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_author"), "book", ["author"], unique=False)
    op.create_index(op.f("ix_book_name"), "book", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_name"), table_name="book")
    op.drop_index(op.f("ix_book_author"), table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
